

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations, Html } from '@react-three/drei'
import Contact_Card_Face from '../faces/Contact_Card_Face'

export default function Business_Card(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/final_models/Businessfinal.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="ArmatureWallet"
          position={[-7.081, 0.626, -1.709]}
          rotation={[0, 0, -Math.PI / 2]}>
          <skinnedMesh
            name="BuisCard"
            geometry={nodes.BuisCard.geometry}
            material={materials.Buisness_Material}
            skeleton={nodes.BuisCard.skeleton}
          />
          <primitive object={nodes.walletstay}>
            <Html
              occlude="blending"
              wrapperClass="nodes"
              position={[-2.44, 6.5, 0.77]}
              transform
              distanceFactor={8.4}
              rotation-z={THREE.MathUtils.degToRad(-90)}
              rotation-y={THREE.MathUtils.degToRad(179.8)}
              rotation-x={THREE.MathUtils.degToRad(178.56)}
            >
              <Contact_Card_Face />
            </Html>
          </primitive>
          <primitive object={nodes.walletspine} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/final_models/Businessfinal.glb')