

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Business_Card(props) {
  const { nodes, materials } = useGLTF('/final_models/Buisnessfinal.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BuisCard.geometry}
        material={materials.Buisness_Material}
        position={[-1.406, 3.075, -0.984]}
        rotation={[0, -0.022, 0]}
        scale={[5.751, 3.101, 0.445]}
      />
    </group>
  )
}

useGLTF.preload('/final_models/Buisnessfinal.glb')