/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations, Html } from '@react-three/drei'
import { useSpring, animated } from '@react-spring/three'
import DL_Face from './DL_Face.jsx'

export default function DL_Card(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/final_models/DLfinal.glb')
  const { actions, names } = useAnimations(animations, group)
  const cardRef = useRef()

  useEffect(() => {
    actions['WalletOpenAnimation'].setLoop(THREE.LoopOnce, 1);
    actions['WalletOpenAnimation'].clampWhenFinished = true;
    actions['WalletOpenAnimation'].fadeIn(0.5).play()
  }, [])

  const helper = () => {
    console.log('clicked DL')
    // actions['WalletOpenAnimation'].setLoop(THREE.LoopOnce, 1);
    // actions['WalletOpenAnimation'].clampWhenFinished = true;
    // actions['WalletOpenAnimation'].fadeIn(0.5).play()
  }
  // const {dl_position} = useSpring({
  //   from: { dl_position: [-7.081, 0.626, -1.709]},
  //   to: [{dl_position: [-7.081, 8, -1.709]},
  //        {dl_position: [-7.081, 0.626, -1.709]}],
  //   config: {
  //       mass: 5,
  //       tension: 200,
  //       friction: 50,
  //   },
  //   // loop: true,
  //   immediate: true,
  // })

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene" onClick={helper}>
        <animated.group
          name="ArmatureWallet"
          // position={dl_position}
          position={[-7.081, 0.626, -1.709]}
          rotation={[0, 0, -Math.PI / 2]}>
          <skinnedMesh
            ref={cardRef}
            name="DL_Card"
            geometry={nodes.DL_Card.geometry}
            material={materials.DL_Material}
            skeleton={nodes.DL_Card.skeleton}
          />
          <primitive object={nodes.walletstay} />
          <primitive object={nodes.walletspine}>
            <primitive object={nodes.walletopen}>
              <Html
                occlude="blending"
                wrapperClass="nodes"
                position={[2.4, 7, 1.13]}
                transform
                distanceFactor={8}
                rotation-x={THREE.MathUtils.degToRad(-1.4)}
                rotation-z={THREE.MathUtils.degToRad(-90)}
                style={{ pointerEvents: 'none' }}
              >
                <DL_Face />
              </Html>
            </primitive>
          </primitive>

        </animated.group>
      </group>
    </group>
  )
}

useGLTF.preload('/final_models/DLfinal.glb')