

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Project5_Card(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/final_models/Proj5final.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="ArmatureSleeve" position={[-0.01, 0, -0.758]}>
          <skinnedMesh
            name="Proj5Card"
            geometry={nodes.Proj5Card.geometry}
            material={materials.Project_Material}
            skeleton={nodes.Proj5Card.skeleton}
          />
          <primitive object={nodes.firstfold} />
          <primitive object={nodes.firstsleeve} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/final_models/Proj5final.glb')