

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, useAnimations, Html } from '@react-three/drei'
import Project_Card_Face from './Project_Card_Face'

export default function Project1_Card(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/final_models/Proj1final.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="ArmatureSleeve" position={[-0.01, 0, -0.758]}>
          <skinnedMesh
            name="Proj1Card"
            geometry={nodes.Proj1Card.geometry}
            material={materials.Project_Material}
            skeleton={nodes.Proj1Card.skeleton}
          />
          <primitive object={nodes.firstfold} />
          <primitive object={nodes.firstsleeve}>
            <Html
              occlude="blending"
              wrapperClass="nodes"
              position={[-4.1, 2.67, 0.26]}
              transform
              distanceFactor={8.2}
              rotation-y={THREE.MathUtils.degToRad(1.03)}
              style={{ pointerEvents: 'none' }}
            >
              <Project_Card_Face number={1} />
            </Html>
          </primitive>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/final_models/Proj1final.glb')