

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Wallet(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/final_models/walletfinal.glb')
  const { actions } = useAnimations(animations, group)
  const [isOpened, setIsOpened] = useState(false)

  const helper = () => {
    console.log('clicked wallet')
    
    if(!isOpened) {
        actions['WalletCloseAnimation'].fadeOut(0.5)
        actions['WalletOpenAnimation'].reset()
        actions['WalletOpenAnimation'].setLoop(THREE.LoopOnce, 1);
        actions['WalletOpenAnimation'].clampWhenFinished = true;
        actions['WalletOpenAnimation'].fadeIn(0.5).play()
        console.log('opening')
        setIsOpened(true)
    } else {
        actions['WalletOpenAnimation'].fadeOut(0.5)
        actions['WalletCloseAnimation'].reset()
        actions['WalletCloseAnimation'].setLoop(THREE.LoopOnce, 1);
        actions['WalletCloseAnimation'].clampWhenFinished = true;
        actions['WalletCloseAnimation'].fadeIn(0.5).play()
        console.log('closing')
        setIsOpened(false)
    }
  }

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene" onClick={helper}>
        <group name="ArmatureSleeve" position={[-0.01, 0, -0.758]}>
          <skinnedMesh
            name="Sleeve"
            geometry={nodes.Sleeve.geometry}
            material={materials.Sleeve_Material}
            skeleton={nodes.Sleeve.skeleton}
          />
          <primitive object={nodes.firstfold} />
          <primitive object={nodes.firstsleeve} />
        </group>
        <group
          name="ArmatureWallet"
          position={[-7.081, 0.626, -1.709]}
          rotation={[0, 0, -Math.PI / 2]}>
          <group name="Wallet">
            <skinnedMesh
              name="Cube"
              geometry={nodes.Cube.geometry}
              material={materials.Wallet_Material}
              skeleton={nodes.Cube.skeleton}
            />
            <skinnedMesh
              name="Cube_1"
              geometry={nodes.Cube_1.geometry}
              material={materials.Sleeve_Material}
              skeleton={nodes.Cube_1.skeleton}
            />
          </group>
          <primitive object={nodes.walletstay} />
          <primitive object={nodes.walletspine} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/final_models/walletfinal.glb')