

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Wallet6(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/walletnodl.glb')
  const { actions, names } = useAnimations(animations, group)
  const [isOpened, setIsOpened] = useState(false)
  console.log(names)

  const helper = () => {
    console.log('clicked wallet')
    
    if(!isOpened) {
        actions['WalletCloseAnimation'].fadeOut(0.5)
        actions['WalletOpenAnimation'].reset()
        actions['WalletOpenAnimation'].setLoop(THREE.LoopOnce, 1);
        actions['WalletOpenAnimation'].clampWhenFinished = true;
        actions['WalletOpenAnimation'].fadeIn(0.5).play()
        console.log('opening')
        setIsOpened(true)
    } else {
        actions['WalletOpenAnimation'].fadeOut(0.5)
        actions['WalletCloseAnimation'].reset()
        actions['WalletCloseAnimation'].setLoop(THREE.LoopOnce, 1);
        actions['WalletCloseAnimation'].clampWhenFinished = true;
        actions['WalletCloseAnimation'].fadeIn(0.5).play()
        console.log('closing')
        setIsOpened(false)
    }
  }

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene" onClick={helper}>
        <mesh
          name="BuisCard"
          castShadow
          receiveShadow
          geometry={nodes.BuisCard.geometry}
          material={materials.Buisness_Material}
          position={[-1.406, 3.075, -0.984]}
          rotation={[0, -0.022, 0]}
          scale={[5.751, 3.101, 0.445]}
        />
        <mesh
          name="Proj1Card"
          castShadow
          receiveShadow
          geometry={nodes.Proj1Card.geometry}
          material={materials.Project_Material}
          position={[0.421, 3.084, -0.785]}
          rotation={[0, -0.026, 0]}
          scale={[5.751, 3.101, 0.445]}
        />
        <group name="ArmatureSleeve" position={[-0.01, 0, -0.758]}>
          <skinnedMesh
            name="Sleeve"
            geometry={nodes.Sleeve.geometry}
            material={materials.Sleeve_Material}
            skeleton={nodes.Sleeve.skeleton}
          />
          <primitive object={nodes.firstfold} />
          <primitive object={nodes.firstsleeve} />
        </group>
        <group
          name="ArmatureWallet"
          position={[-7.081, 0.626, -1.709]}
          rotation={[0, 0, -Math.PI / 2]}>
          <group name="Wallet">
            <skinnedMesh
              name="Cube"
              geometry={nodes.Cube.geometry}
              material={materials.Wallet_Material}
              skeleton={nodes.Cube.skeleton}
            />
            <skinnedMesh
              name="Cube_1"
              geometry={nodes.Cube_1.geometry}
              material={materials.Sleeve_Material}
              skeleton={nodes.Cube_1.skeleton}
            />
          </group>
          <primitive object={nodes.walletstay} />
          <primitive object={nodes.walletspine} />
        </group>
        <mesh
          name="Proj2Card"
          castShadow
          receiveShadow
          geometry={nodes.Proj2Card.geometry}
          material={materials.Project_Material}
          position={[0.421, 3.084, -0.514]}
          rotation={[0, -0.03, 0]}
          scale={[5.751, 3.101, 0.445]}
        />
        <mesh
          name="Proj3Card"
          castShadow
          receiveShadow
          geometry={nodes.Proj3Card.geometry}
          material={materials.Project_Material}
          position={[0.421, 3.084, -0.233]}
          rotation={[0, -0.043, 0]}
          scale={[5.751, 3.101, 0.445]}
        />
        <mesh
          name="Proj4Card"
          castShadow
          receiveShadow
          geometry={nodes.Proj4Card.geometry}
          material={materials.Project_Material}
          position={[0.421, 3.084, 0.032]}
          rotation={[0, -0.043, 0]}
          scale={[5.751, 3.101, 0.445]}
        />
        <mesh
          name="Proj5Card"
          castShadow
          receiveShadow
          geometry={nodes.Proj5Card.geometry}
          material={materials.Project_Material}
          position={[0.421, 3.084, 0.399]}
          rotation={[0, -0.056, 0]}
          scale={[5.751, 3.101, 0.445]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/walletnodl.glb')




/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import * as THREE from 'three'
// import React, { useRef } from 'react'
// import { useGLTF, useAnimations } from '@react-three/drei'

// export function Wallet6(props) {
//   const group = useRef()
//   const { nodes, materials, animations } = useGLTF('/walletnodl.glb')
//   const { actions, names } = useAnimations(animations, group)

//   const helper = () => {
//     console.log('clicked wallet')
//     // actions[names[0]].fadeIn(0.5).play()
//     // actions[names[1]].fadeIn(0.5).play()
//     actions[names[0]].setLoop(THREE.LoopOnce, 1);
//     actions[names[0]].clampWhenFinished = true; // Stop at the last frame
//     actions[names[0]].fadeIn(0.5).play()
//     actions[names[1]].setLoop(THREE.LoopOnce, 1);
//     actions[names[1]].clampWhenFinished = true; // Stop at the last frame
//     actions[names[1]].fadeIn(0.5).play()

//   }

//   return (
//     <group ref={group} {...props} dispose={null}>
//       <group name="Scene" onClick={helper}>
//         <mesh
//           name="BuisCard"
//           castShadow
//           receiveShadow
//           geometry={nodes.BuisCard.geometry}
//           material={materials.Buisness_Material}
//           position={[-1.406, 3.075, -0.984]}
//           rotation={[0, -0.022, 0]}
//           scale={[5.751, 3.101, 0.445]}
//         />
//         <mesh
//           name="Proj1Card"
//           castShadow
//           receiveShadow
//           geometry={nodes.Proj1Card.geometry}
//           material={materials.Project_Material}
//           position={[0.421, 3.084, -0.785]}
//           rotation={[0, -0.026, 0]}
//           scale={[5.751, 3.101, 0.445]}
//         />
//         <group name="ArmatureSleeve" position={[-0.01, 0, -0.758]}>
//           <skinnedMesh
//             name="Sleeve"
//             geometry={nodes.Sleeve.geometry}
//             material={materials.Sleeve_Material}
//             skeleton={nodes.Sleeve.skeleton}
//           />
//           <primitive object={nodes.firstfold} />
//           <primitive object={nodes.firstsleeve} />
//         </group>
//         <group
//           name="ArmatureWallet"
//           position={[-7.081, 0.626, -1.709]}
//           rotation={[0, 0, -Math.PI / 2]}>
//           <group name="Wallet">
//             <skinnedMesh
//               name="Cube"
//               geometry={nodes.Cube.geometry}
//               material={materials.Wallet_Material}
//               skeleton={nodes.Cube.skeleton}
//             />
//             <skinnedMesh
//               name="Cube_1"
//               geometry={nodes.Cube_1.geometry}
//               material={materials.Sleeve_Material}
//               skeleton={nodes.Cube_1.skeleton}
//             />
//           </group>
//           <primitive object={nodes.walletstay} />
//           <primitive object={nodes.walletspine} />
//         </group>
//         <mesh
//           name="Proj2Card"
//           castShadow
//           receiveShadow
//           geometry={nodes.Proj2Card.geometry}
//           material={materials.Project_Material}
//           position={[0.421, 3.084, -0.514]}
//           rotation={[0, -0.03, 0]}
//           scale={[5.751, 3.101, 0.445]}
//         />
//         <mesh
//           name="Proj3Card"
//           castShadow
//           receiveShadow
//           geometry={nodes.Proj3Card.geometry}
//           material={materials.Project_Material}
//           position={[0.421, 3.084, -0.233]}
//           rotation={[0, -0.043, 0]}
//           scale={[5.751, 3.101, 0.445]}
//         />
//         <mesh
//           name="Proj4Card"
//           castShadow
//           receiveShadow
//           geometry={nodes.Proj4Card.geometry}
//           material={materials.Project_Material}
//           position={[0.421, 3.084, 0.032]}
//           rotation={[0, -0.043, 0]}
//           scale={[5.751, 3.101, 0.445]}
//         />
//         <mesh
//           name="Proj5Card"
//           castShadow
//           receiveShadow
//           geometry={nodes.Proj5Card.geometry}
//           material={materials.Project_Material}
//           position={[0.421, 3.084, 0.399]}
//           rotation={[0, -0.056, 0]}
//           scale={[5.751, 3.101, 0.445]}
//         />
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('/walletnodl.glb')